In [31]:
class MulGraph:
    
    def _init__(self):
        self.x = None
        self.y = None
    
    def forward(self,x,y):
        self.x = x
        self.y = y
        
        out = x * y
        return out
    
    def backward(self, dout):
        
        dx = dout*self.y
        dy = dout*self.x

        return dx, dy

In [38]:
class AddGraph:
    def __init__(self):
        pass
    
    def forward(self,x,y):
        out = x+y
        return out
    
    def backward(self,dout):
        dx = dout*1
        dy = dout*1
        return dx, dy

In [42]:
x1 = 5
x2 = 3
x3 = 4
f1 = AddGraph()
f2 = AddGraph()
part_sum = f1.forward(x1,x2)
total_sum = f2.forward(part_sum,x3)

In [43]:
dout = 1
df1, dx3 = f2.backward(dout)

In [45]:
dx3

1

In [20]:
apple = 100
number = 2
tax = 1.1

cal_apple = ComputeGraph()
cal_tax = ComputeGraph()
apple_price = cal_apple.forward(apple,number)
total_price = cal_tax.forward(apple_price,tax)

In [25]:
dout = 1
dapple_price,dtax = cal_tax.backward(dout)

In [28]:
dout = dapple_price 
dapple, dnumber = cal_apple.backward(dout)

In [30]:
dnumber

110.00000000000001

In [15]:
dout = 1
dnumber, dapple = cal_apple.backward(dout)
dapple_price, dtax = cal_tax.backward(dout)

In [19]:
apple = 100
apple_num = 2
orange = 150
orange_num = 3
tax = 1.1
#total_price
#dApple
#dOrange
#dOrange
#dOrange_num
#dTax

200

In [62]:
class MulLayer:
    def __init__(self):
        self.x = None
        self.y = None
    
    def forward(self,x,y):
        self.x = x 
        self.y = y
        out = self.x*self.y
        return out
    def backward(self,dout):
        dx = dout*self.y
        dy = dout*self.x
        return dx, dy
class AddLayer:
    def __init__(self):
        pass
    def forward(self,x,y):
        out = x + y
        return out
    def backward(self,dout):
        dx = dout*1
        dy = dout*1
        return dx, dy
        

In [63]:
apple = 100
apple_num = 2
orange = 150
orange_num = 3
tax = 1.1
#total_price
#dApple
#dApple_num
#dOrange
#dOrange_num
#dTax

In [64]:
mul_apple_layer = MulLayer()
mul_orange_layer = MulLayer()
add_apple_orange_layer = AddLayer()
mul_tax_layer = MulLayer()

In [65]:
apple_price = mul_apple_layer.forward(apple,apple_num)
orange_price = mul_orange_layer.forward(orange, orange_num)

In [66]:
price = add_apple_orange_layer.forward(apple_price,orange_price)

In [68]:
total_price = mul_tax_layer.forward(price,tax)

In [75]:
dout = 1
dprice,dtax = mul_tax_layer.backward(dout)

In [77]:
dapple, dorange = add_apple_orange_layer.backward(dprice)

In [78]:
dApple, dApple_num = mul_apple_layer.backward(dapple)
dOrange, dOrange_num = mul_orange_layer.backward(dorange)

In [84]:
dOrange_num

165.0

In [85]:
def relu(x):
    return np.where(x > 0, x, 0)

In [99]:
class Relu:
    def __init__(self):
        self.mask = None
    
    def forward(self,x):
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0
        return out       
        
    def backward(self,dout):
        dout[self.mask] = 0
        dx = dout
        return dx

In [138]:
class Sigmoid:
    def __init_(self):
        self.out = None
    
    def forward(self,x):
        out = 1 / (1+np.exp(-x))
        self.out = out
        return out 
    
    def backward(self,dout):
        dx = dout*self.out*(1-self.out)
        return dx

In [139]:
X = np.random.randn(2)
W = np.random.randn(2,3)
b = np.random.randn(3)

In [ ]:
class Affine:
    

In [163]:
x = np.array([[0,0,0],[10.,10,10]])
b = np.array([1,2,3])
out = x+b

In [164]:
dy = np.arange(1,7).reshape(2,3)

In [169]:
dB = np.sum(dy, axis=0)

In [170]:
dB

array([5, 7, 9])

In [175]:
class Affine:
    def __init__(self,W,b):
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None
    
    def forward(self,x):
        self.x = x
        out = np.dot(x,self.W) + self.b
        
        return out
    
    def backward(self,dout):
        
        dx = np.dot(dout, self.W.T)
        self.dW = np.dot(self.x.T,dout)
        self.db = np.sum(dout,axis=0)
        
        return dx

In [183]:
x = np.random.randn(4,2)
W = np.random.randn(2,3)
b = np.random.randn(3)

In [184]:
affine = Affine(W,b)

In [ ]:
out = affine.forward(x)

In [ ]:
affine.backward(out)

array([[-8.18435951,  0.56471461],
       [ 7.93715958,  1.17822735],
       [-2.3962259 ,  1.82793382],
       [ 5.73454589,  2.24728797]])

In [ ]:
affine.db

array([ 3.29149053, -0.99255077, -3.9090872 ])

In [200]:
x = np.random.randn(5,3)
w1 = np.random.randn(3,4)
b1 = np.random.randn(4)
w2 = np.random.randn(4,3)
b2 = np.random.randn(3)
t = np.zeros((5,3))
t[:,1] = 1

In [210]:
from loss import cross_entropy_error
from activation import softmax
def relu(x):
    return np.maximum(0,x)
l1 = np.dot(x,w1) + b1
z1 = relu(l1)
l2 = np.dot(z1,w2) + b2
cross_entropy_error(softmax(l2),t)

0.8177568142634734

In [207]:
class SoftmaxWithLoss:
    def __init__(self):
        self.loss = None
        self.y = None
        self.t = None
    
    def forward(self,x,t):
        self.y = softmax(x)
        self.t = t
        self.loss = cross_entropy_error(self.y,self.t)
        return self.loss
    
    def backward(self,dout=1):
        dx = dout*(self.y - self.t)/y.shape[0]
        return dx

In [208]:
dL = SoftmaxWithLoss() 

In [209]:
dLforward = dL.forward(l2,t)

In [213]:
dL.backward().shape

(5, 3)

In [214]:
l2.shape

(5, 3)