In [3]:
import numpy as np
from activation import softmax, sigmoid, relu
from loss import mse, cross_entropy_err
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784')

In [4]:
x = mnist['data']
y = mnist['target']

In [8]:
y = y.astype(np.int)
t = np.zeros((y.size,np.unique(y).size))

/tmp/ipykernel_6923/3609945712.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = y.astype(np.int)


In [9]:
for i in range(y.size):
    t[i,y[i]] = 1

In [70]:
def SimpleLayer(x,y):
    W = np.random.randn(x,y)
    b = np.random.randn(y)
    network = {'W':W, 'b':b}
    return network

In [126]:
def softmax(x):
    c = np.max(x,axis=1).reshape(-1,1)
    a = x - c
    return np.exp(a)/np.sum(np.exp(a),axis=1).reshape(-1,1)

In [125]:
x = np.random.randn(4,3)
softmax(x)

array([[0.44321242, 0.34545059, 0.21133699],
       [0.33196447, 0.58074333, 0.08729219],
       [0.22921003, 0.10386444, 0.66692554],
       [0.61530046, 0.01570133, 0.36899821]])

In [124]:
np.max(x,axis=1).reshape(-1,1)

array([[ 1.62154334],
       [ 0.72978897],
       [-0.39557551],
       [ 0.88169861]])

In [71]:
init_network = SimpleLayer(x.shape[1],t.shape[1])

In [72]:
W, b = init_network['W'], init_network['b']

In [118]:
y = softmax(np.dot(x,W)+b)

In [119]:
y

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 2.01486510e-269, 1.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        4.79634262e-106, 0.00000000e+000, 0.00000000e+000],
       ...,
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 1.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 1.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 1.00000000e+000]])

In [103]:
c = np.max(x,axis=1)

In [104]:
c

0        255.0
1        255.0
2        255.0
3        255.0
4        255.0
         ...  
69995    255.0
69996    254.0
69997    255.0
69998    255.0
69999    254.0
Length: 70000, dtype: float64

In [74]:
cross_entropy_err(y,t)

1.4031251040944408

In [61]:
np.dot(x,init_network['W']).shape

(70000, 10)

In [18]:
np.random.randint(10,100,1)

array([13])

In [39]:
init_network['W'].shape

(70000, 10)

In [92]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
        
    if t.size == y.size:
        t = t.argmax(axis=1)
             
    batch_size = y.shape[0]
    return -np.sum(np.log(y+ 1e-7)) / batch_size


In [93]:
cross_entropy_error(y,t)

1015035.0907345656

In [95]:
y.shape

(10, 70000)

In [145]:
def fx(x):
    return x**3 - 3*x**2 + 3

In [136]:
def _diff(f,x):
    h = 1e-5
    fx = f
    return (fx(x+h)-fx(x))/h

In [147]:
_diff(fx,np.array([1,2,3]))

array([-3.00000000e+00,  3.00001801e-05,  9.00006000e+00])

In [149]:
def cross_entropy_err(y,t):
    delta = 1e-7
    return np.sum(-np.sum(t*np.log(y+delta)))/y.size

In [ ]:
y = x1**2+x2**2

In [168]:
def f2(x):
    return np.sum(x**2,axis=1)

(10, 1)

In [155]:
x = np.random.randint(1,10,20).reshape(10,2)

In [169]:
_diff(f2,x).shape

(10,)

In [ ]:
def _diff2(x):
    return

In [175]:
x = np.random.randint(90,100,20).reshape(10,2)

In [207]:
x1 = np.random.randn(100)
x2 = np.random.randn(100)
x3 = np.random.randn(100)
y = 2.5*x1 + 3.2*x2 + 4.1*x3

In [284]:
w1 = np.random.randn(1).reshape(1,1)

In [292]:
w1

array([[1.80655767]])

In [299]:
lr = 1e-3
for i in range(10000):
    delta = 1e-7
    fx_h = mse(np.dot(x1.reshape(-1,1),w1+delta),y)   
    fx = mse(np.dot(x1.reshape(-1,1),w1),y)
    w1 = w1 - lr*((fx_h - fx)/delta)

In [311]:
w3 = np.array([10]).reshape(-1,1)

In [324]:
W.size

3

In [319]:
lr = 1e-5
for i in range(1000000):
    delta = 1e-7
    fx_h = mse(np.dot(x3.reshape(-1,1),w3+delta),y)   
    fx = mse(np.dot(x3.reshape(-1,1),w3),y)
    w3 = w3 - lr*((fx_h - fx)/delta)

In [331]:
W[i].shape

(1,)

In [332]:
i = 0
delta = 1e-7
mse(np.dot(X[:,i].reshape(-1,1),W[i].reshape(1,-1)+delta),y)

19.54503305731955

In [338]:
def grad(x,y,w):
    delta = 1e-7
    tmp = np.random.randn(1)[0]
    for i in range(w.size):
        fx_h = mse(np.dot(x[:,i].reshape(-1,1),w[i].reshape(1,-1)+delta),y)
        fx = mse(np.dot(x[:,i].reshape(-1,1),w[i].reshape(1,-1)),y)
        tmp = tmp - lr*((fx_h-fx)/delta)
        print(tmp)
    return tmp

In [339]:
grad(X,y,W)

0.42128142650819655
0.4212740384827163
0.42127732168469323


0.42127732168469323

In [180]:
X = np.c_[x1,x2,x3].reshape(100,3)

In [258]:
W = np.random.randn(3,1)

In [227]:
fx = w1*x1 + w2*x2 + w3*x3

array([[ 0.77528293],
       [-0.44244975],
       [-0.62173236]])

In [229]:
W

array([[ 0.77498641],
       [-0.44274628],
       [-0.62202888]])

In [185]:
y = y.reshape(-1,1)

In [186]:
def fx(X,W):
    return np.dot(X,W)

In [220]:
def mse(y,t):
    return (1/2*np.sum((y-t)**2))/y.size

In [234]:
y = y.reshape(-1,1)

In [293]:
delta = 1e-5
lr = 1e-5
for i in range(1000000):
    W = W - lr*((mse(np.dot(X,(W+delta)),y)-mse(np.dot(X,W),y))/delta)

KeyboardInterrupt: 

In [278]:
mse(np.dot(X,W),y)

19.17694952337466

In [279]:
W

array([[-0.85669618],
       [ 1.05758821],
       [ 0.79703159]])

In [230]:
(mse(np.dot(X,(W-delta)),y)-mse(np.dot(X,W),y))/delta

29.74197022922453

In [224]:
for i in range(100):
    W = W - 1e-7*mse(np.dot(X,W),y)
    print(W,"=======",mse(np.dot(X,W),y))

[[ 0.08468969]
 [-1.0883317 ]
 [-0.4998475 ]] ======= 2035.8495080585667
[[ 0.08448611]
 [-1.08853529]
 [-0.50005108]] ======= 2035.8843968143117
[[ 0.08428252]
 [-1.08873888]
 [-0.50025467]] ======= 2035.919298713317
[[ 0.08407893]
 [-1.08894247]
 [-0.50045826]] ======= 2035.9542137564529
[[ 0.08387533]
 [-1.08914606]
 [-0.50066186]] ======= 2035.9891419445894
[[ 0.08367174]
 [-1.08934966]
 [-0.50086546]] ======= 2036.024083278599
[[ 0.08346813]
 [-1.08955326]
 [-0.50106906]] ======= 2036.0590377593517
[[ 0.08326453]
 [-1.08975687]
 [-0.50127267]] ======= 2036.09400538772
[[ 0.08306092]
 [-1.08996048]
 [-0.50147628]] ======= 2036.128986164576
[[ 0.0828573 ]
 [-1.09016409]
 [-0.50167989]] ======= 2036.1639800907928
[[ 0.08265369]
 [-1.09036771]
 [-0.50188351]] ======= 2036.198987167242
[[ 0.08245007]
 [-1.09057133]
 [-0.50208713]] ======= 2036.2340073947976
[[ 0.08224645]
 [-1.09077495]
 [-0.50229075]] ======= 2036.2690407743335
[[ 0.08204282]
 [-1.09097858]
 [-0.50249438]] ======= 203

In [198]:
mse(np.dot(X,W),y)

nan

In [ ]:
def _diff(f,y,t):
    h = 1e-5
    fx = f
    return (fx(x+h)-fx(x))/h