In [212]:
from activation import sigmoid, softmax, relu
from loss import mse, cross_entropy_err
import pickle
import numpy as np
import matplotlib.pyplot as plt

In [135]:
from sklearn.datasets import fetch_openml

In [136]:
mnist = fetch_openml('mnist_784')

In [186]:
x = mnist['data']
y = mnist['target']

In [138]:
with open('sample_weight.pkl','rb') as f:
    network = pickle.load(f)

In [82]:
def predict(x):
    W1 = weight['W1']
    W2 = weight['W2']
    W3 = weight['W3']
    b1, b2, b3 = weight['b1'], weight['b2'], weight['b3']
    h1 = np.dot(x,W1) + b1
    a1 = sigmoid(h1)
    h2 = np.dot(a1,W2) + b2
    a2 = sigmoid(h2)
    out = np.dot(a2,W3) + b3
    out = np.argmax(out,axis=1).astype('str')
    return out

def accuracy(x,y):
    return sum(predict(x) == y.values)/y.size

In [209]:
def predict(x,network):
    input_layer = x
    layers = []
    bias = []
    num_layer = int(len(network.keys())/2)
    for i in range(num_layer):
        layers.append(network['W'+str(i+1)])
        bias.append(network['b'+str(i+1)])
    for i in range(num_layer):
        if num_layer != i:
            input_layer = sigmoid(np.dot(input_layer,layers[i]) + bias[i])
        else:
            input_layer = np.dot(input_layer,layers[i]) + bias[i]
    return input_layer

In [169]:
tf = np.array([0,1,0,0,0,0,0,0,0,0])

In [170]:
tt = np.array([0,0,0,0,1,0,0,0,0,0])

In [174]:
yt = softmax(predict(x,network)[0])
yf = softmax(predict(x,network)[24])

In [179]:
-np.sum(yf*np.log(tf+1e-7))

13.797414852781706

In [176]:
1/2*np.sum((yt-tt)**2)

0.4993157237738211

In [158]:
p = softmax(f)

In [161]:
1/2*np.sum((f-r)**2)

1.799511709333263

In [145]:
y[predict(x,network) != y]

24       1
48       9
70       1
80       9
100      5
        ..
69970    5
69975    3
69982    5
69986    3
69998    5
Name: class, Length: 5282, dtype: category
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [123]:
# y 값을 one_hot -- tk
# network softmax
def f(x):
    return x**2

In [125]:
def der_f(x):
    return 2*x

In [126]:
der_f(3)

6

In [128]:
(f(3+1e-7) - f(3))/1e-7

6.000000087880153

In [121]:
sum(pre == y)/y.size

0.8191285714285714

In [100]:
for i in range(int(len(network.keys())/2)):
    print('W'+str(i+1))
    print('b'+str(i+1))


W1
b1
W2
b2
W3
b3


In [118]:
relu(np.dot(x,network['W1']))

array([[ 991.38860958,    0.        ,    0.        , ...,  461.81789378,
           0.        ,    0.        ],
       [1251.53191894,  865.42200546,    0.        , ...,  297.65761123,
           0.        ,   43.0190886 ],
       [   0.        ,  384.96450885,  522.83004731, ...,    0.        ,
         359.95052797,  276.16372561],
       ...,
       [   0.        ,    0.        ,  620.68962102, ...,    0.        ,
         507.20683358,  220.44589879],
       [   0.        ,    0.        ,    0.        , ...,    0.        ,
         350.09469865,   55.06031603],
       [ 757.27764039, 1793.27601436,    0.        , ...,    0.        ,
         587.88680071,  933.27330242]])

In [129]:
import numpy as np

In [132]:
softmax(np.array([100,200,300]))

array([1.38389653e-87, 3.72007598e-44, 1.00000000e+00])

In [133]:
softmax(np.array([0.7,70,4]))

array([8.00557267e-31, 1.00000000e+00, 2.17052201e-29])

In [181]:
def mse(y,t):
    return (1/2*np.sum((y-t)**2))*y.size

In [182]:
def cross_entropy_err(y,t):
    return np.sum(-np.sum(t*np.log(y)))/y.size

In [187]:
y = y.values.astype(np.int)

/tmp/ipykernel_3943/2727405977.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = y.values.astype(np.int)


In [199]:
y_one = np.zeros((y.size,np.unique(y).size))

In [210]:
mse(predict(x,network),y_one)

67948315688.16142

In [211]:
cross_entropy_err(predict(x,network),y_one)

0.0010418838073685257